travis:
  secure:
    BINSTAR_TOKEN: lGN8ryQJCNagU2ULTKq17TYDtk8DrpjMS4xHQONZnL7ZwHXiVZmhvy1X7GGJEAWI9GIEGHicER1i4lLVkK7fYvf757zu3CxBVWM1SncBDFUISGw28OxbFmIN3zNq9fB+HY7Is/YOoc0Q8297IeYUjjFeWBzToCLc8I5aghTxx5GFdvVhbnmcm4FGS73W1BYpnOLWl40TO5o0habmoqxM7NOa6tVbh3J02HWp0Yiv4PRJeU3vORdOANGn7bCUxYvr7Vzlpb21dnIlRrxknmj6qZX7TOWkVYLsrDJmtpUAamyr+O7PHi/El6i+kHODCQHqpH/XNJQ235l0XS+UgbZLgrn1etjbZGKnJj7Q4dmviwjRjIZYmRKDX5IPuOqkQWsh1vXC83kNN2sWYdoEg7zme9OZqmtHC/UTUsGpTx4AwuFX0WNWTkb2xRgW6PvcqndMmenwnftIjU+uqSqGJl43DqjIpgsrn4C+RMQh0lDpcubeT5ckUgFZMu3LFCpJwy80GpbRiM+ImXTrK9J+28xgmibqJP4VjcmS6QWbP/GRC1lrZNGpcPxZaVuDne0tcTtGVOaimTpCCVFCHQSJSaKWuASy6WGuk/zMhMCnZXZHpp4sDTsk0t4theSk0oQ3+iQhsDF5eYFvHERQNd7Rs/66hvubK06JWnFnbIT1mIR3WDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
