travis:
  secure:
    BINSTAR_TOKEN: CsBzMI/Mf251adSS/3F2euu9L8aptPbk8fbdU8pMpxOad1IcEDiAXrKX23zao+E20Oszeg2Y3axndd7zfPmcXvBSPUI1HicFTl93+Ta33AH1gdR97W/6F4xLrXK9AUi13RerSJ/2GX0tRrg2lHkXBdSwLU6JhrdL5Ba/o1n/sYGv+LS+qND8a4nuvqnnQEI/iE+j3ql/qkmQZMkts1w8Y88lcMr6+37P5b2xYlA41j1cCpNYfQzuDCUp2b1sc6f7MeTgfV+GFixd/5sy/bHCeGHYr/1YhIl0QIN1oanaLyhopyuMu7EOfcTPicP1VEQhi8RRD5TMc2P3URdGE/IT7HcQotzZS92UW7Sx/+1XHpYxXe4/HbxW2HzuGQcTsU2jnchkb0UQ5ysuh/qlRx/CSh9uW+jqXlkRanVfWtZFOZ7PNzBeejRGUkfYuz4aTKrNaOf6Hwi3WrL95FqB+fAkNksQ5B59oRYqFN13vFeGQQCinagfw43t5pIFdBI31GTsBb79p8zt9ROlduH+MsCqmCH9Mh5llhu7xUi4kg7ocZJuoIXRb1f5uGkTIKrfd2xOZuxHmMvRugbBUFRtmSN7BNKiUKBKdvOhydevUQvS7ciqu1rSlP6VIBCNLbBIn3UIbmVYZCgl/C62+XnJOYrzl2PBWuepgnXxmDdMplCD6Jw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
